name: Visualize

on:
  push:
    branches: [main]

jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: diagram.svg
          artifact_name: diagramgarten
          should_push: false
          excluded_paths: 'dist,node_modules'
      - name: artifact
        uses: actions/download-artifact@v2
        with:
          name: diagramgarten
          path: "downloads"
